//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordinate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coordinate()
        {
            this.U_Collect_Coordinate = new HashSet<U_Collect_Coordinate>();
            this.U_Dislike_Coordinate = new HashSet<U_Dislike_Coordinate>();
        }
    
        public int CoordinateID { get; set; }
        public Nullable<int> CoatID { get; set; }
        public Nullable<int> ShirtID { get; set; }
        public Nullable<int> NetherGarmentID { get; set; }
        public Nullable<int> SuitID { get; set; }
    
        public virtual Coat Coat { get; set; }
        public virtual NetherGarment NetherGarment { get; set; }
        public virtual Shirt Shirt { get; set; }
        public virtual Suit Suit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<U_Collect_Coordinate> U_Collect_Coordinate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<U_Dislike_Coordinate> U_Dislike_Coordinate { get; set; }
    }
}
