//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsComment()
        {
            this.ComReply = new HashSet<ComReply>();
            this.GoodsCommentsLike = new HashSet<GoodsCommentsLike>();
        }
    
        public int GoodsCommentID { get; set; }
        public string ComContent { get; set; }
        public string ComImage { get; set; }
        public string Video { get; set; }
        public Nullable<bool> ImageOrNot { get; set; }
        public Nullable<bool> VideoOrNot { get; set; }
        public int UserID { get; set; }
        public int GoodsID { get; set; }
        public Nullable<System.DateTime> ComTime { get; set; }
        public Nullable<int> ThumbNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComReply> ComReply { get; set; }
        public virtual Goods Goods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsCommentsLike> GoodsCommentsLike { get; set; }
        public virtual Users Users { get; set; }
    }
}
