//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class yichuEntities : DbContext
    {
        public yichuEntities()
            : base("name=yichuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<Coat> Coat { get; set; }
        public virtual DbSet<Collect> Collect { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<ComReply> ComReply { get; set; }
        public virtual DbSet<Coordinate> Coordinate { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<Goods_Color> Goods_Color { get; set; }
        public virtual DbSet<Goods_Size> Goods_Size { get; set; }
        public virtual DbSet<GoodsComment> GoodsComment { get; set; }
        public virtual DbSet<GoodsCommentsLike> GoodsCommentsLike { get; set; }
        public virtual DbSet<GoodsLike> GoodsLike { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<NetherGarment> NetherGarment { get; set; }
        public virtual DbSet<Note> Note { get; set; }
        public virtual DbSet<NoteComment> NoteComment { get; set; }
        public virtual DbSet<NoteLike> NoteLike { get; set; }
        public virtual DbSet<NoteSelect> NoteSelect { get; set; }
        public virtual DbSet<NoteTrasmit> NoteTrasmit { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Privatemessage> Privatemessage { get; set; }
        public virtual DbSet<Shirt> Shirt { get; set; }
        public virtual DbSet<Size> Size { get; set; }
        public virtual DbSet<Suit> Suit { get; set; }
        public virtual DbSet<U_Attention_U> U_Attention_U { get; set; }
        public virtual DbSet<U_Collect_Coordinate> U_Collect_Coordinate { get; set; }
        public virtual DbSet<U_Dislike_Coordinate> U_Dislike_Coordinate { get; set; }
        public virtual DbSet<U_Reply_NoteComment> U_Reply_NoteComment { get; set; }
        public virtual DbSet<U_Reply_VideoComment> U_Reply_VideoComment { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Video> Video { get; set; }
        public virtual DbSet<VideoComment> VideoComment { get; set; }
        public virtual DbSet<VideoLike> VideoLike { get; set; }
        public virtual DbSet<VideoSelect> VideoSelect { get; set; }
        public virtual DbSet<VideoTrasmit> VideoTrasmit { get; set; }
        public virtual DbSet<Wardrobe> Wardrobe { get; set; }
        public virtual DbSet<GGCC> GGCC { get; set; }
        public virtual DbSet<note_like> note_like { get; set; }
        public virtual DbSet<video_like> video_like { get; set; }
    
        public virtual ObjectResult<Cart_Goods_Result> Cart_Goods(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cart_Goods_Result>("Cart_Goods", useridParameter);
        }
    
        public virtual int Cart_Orders(Nullable<int> userID, string userName, string tel, string address)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("Tel", tel) :
                new ObjectParameter("Tel", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cart_Orders", userIDParameter, userNameParameter, telParameter, addressParameter);
        }
    
        public virtual ObjectResult<OrderDetails_Goods_Result> OrderDetails_Goods(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderDetails_Goods_Result>("OrderDetails_Goods", useridParameter);
        }
    }
}
