//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class video_like
    {
        public int videoid { get; set; }
        public string img { get; set; }
        public string title { get; set; }
        public string intro { get; set; }
        public string adress { get; set; }
        public Nullable<System.DateTime> videotime { get; set; }
        public int videouserid { get; set; }
        public int videolikeid { get; set; }
        public Nullable<System.DateTime> liketime { get; set; }
        public Nullable<int> num { get; set; }
        public int likeuser { get; set; }
    }
}
